name: GCP Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Build assets for production
        run: npm run build

      - name: Build Docker image
        run: docker build -t europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/form-reader-webapp .

      - name: Cleanup
        run: rm -rf node_modules && rm -rf ./client/src

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
  
      - name: Push Docker image to GCP Artifact Registry
        run:  docker push europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/form-reader-webapp

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: form-reader-webapp
          image: europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/form-reader-webapp
          region: europe-central2

