name: GCP Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install dependencies
        run: npm i

      - name: Build assets for production
        run: npm run build

      - name: Cleanup
        run: rm -rf node_modules && rm -rf ./client/src

      - name: Build Docker image
        run: docker build -t europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/form-reader-webapp .

      - name: Push Docker image to GCP Container Registry
        run:  docker push europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/form-reader-webapp 

      - name: Deploy to GCP (Example using Cloud Run)
        run: |-
            gcloud run deploy myapp \
            --image europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/form-reader-webapp \
            --region us-central2 \
            --allow-unauthenticated

